version: '3.8'

services:
  uniqlo-tracker:
    build: .
    container_name: uniqlo-tracker
    restart: unless-stopped
    ports:
      - "${PORT:-3001}:${PORT:-3001}"  # 统一服务端口（API + 前端），可通过环境变量PORT配置
    volumes:
      # 统一挂载数据目录（包含data、logs、reports子目录）
      - ./u-tracker-data:/app/u-tracker-data
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3001}  # 端口配置，默认3001
      - TZ=Asia/Shanghai  # 设置时区
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --no-verbose --tries=1 --spider http://localhost:$${PORT:-3001}/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - uniqlo-network

networks:
  uniqlo-network:
    driver: bridge

# 可选：如果需要使用外部数据库
# volumes:
#   uniqlo-data:
#     driver: local
